name: Deploy script

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t nhk-weather-parser .

      - name: Create config file
        run: echo '${{ secrets.CONFIG }}' > config.json

      - name: Stop and remove existing container if running
        run: |
          docker stop nhk-weather-parser || true
          docker rm nhk-weather-parser || true

      - name: Deploy with Docker
        run: |
          docker run -d --name nhk-weather-parser --restart unless-stopped -v "$(pwd)/config.json:/app/config.json" nhk-weather-parser